#!/usr/bin/env python3
import sys 
import os

path = '/etc/wpa_supplicant/'
files = os.listdir(path)
selection = []

if len(sys.argv) == 2:
    num = int(sys.argv[2])
    selected = True
else:
    selected = False
    
for f in files:
    if f.endswith('.conf') and os.path.isfile(os.path.join(path, f)):
        selection.append(os.path.join(path, f))
        if not selected:
            print(f"Found config [{len(selection)}] :: {f}")
        
if selected:
    if num > len(selection):
        print(f"INVALID ARGS")
        exit
    else:
        try:
            os.system(f"sudo wpa_supplicant -iwlan0 -c{selection[num-1]}")
        except Exception as e:
            print(e)
else:
    num = int(input("Select config: "))
    try:
        os.system(f"sudo wpa_supplicant -iwlan0 -c{selection[num-1]}")
    except Exception as e:
        print(e)

